AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'node_modules/**/*.rb'
    - 'node_modules/**/*.spec'
    - 'bin/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Lint/MissingCopEnableDirective:
  Enabled: false